### ISSUE TITLE
PC software

### ISSUE THREAD

**Issue by ahmaddidiks** [YahboomTechnology/9-axis-IMU-module#1]
Where can I download the PC software for setting up the configuration and showing data in 3D as explained in pdf?

**Comment by YahboomTechnology** [comment]
Click this link to download PC software. [](https://drive.google.com/drive/folders/14WLrL83Xgbh1kMflTg2M7gv6GiIPfjLz?usp=sharing)

**Comment by YahboomTechnology** [comment]
https://drive.google.com/drive/folders/14WLrL83Xgbh1kMflTg2M7gv6GiIPfjLz?usp=sharing
